export const GAME_USERNAME_MAX_LENGTH = 15;
export const GAME_CODE_LENGTH = 4;
export const GAME_CODE_CHARACTERS = '0123456789';
export const FIRST_PLAYER_SCORE_MULTIPLICATOR = 0.2;
export const NEGATIVE_SCORE = -1;
